id: os_directory_services_configured
title: Integrate System into a Directory Services Infrastructure
discussion: |
  The macOS system _MUST_ be integrated into a directory services infrastructure.

  A directory service infrastructure enables centralized user and rights management, as well as centralized control over computer and user configurations. Integrating the macOS systems used throughout an organization into a directory services infrastructure ensures more administrator oversight and security than allowing distinct user account databases to exist on each separate system.
references:
  nist:
    cce:
      macos_15:
        - CCE-94181-5
      macos_14:
        - CCE-92780-6
      macos_13:
        - CCE-91778-1
  disa:
    disa_stig:
      macos_13:
        - APPL-13-000016
  cis:
    controls_v8:
      - 6.7
platforms:
  macOS:
    check: |
      /usr/bin/dscl localhost -list . | /usr/bin/grep -qvE '(Contact|Search|Local|^$)'; /bin/echo $?
    result:
      integer: 0
    fix: |
      Integrate the system into an existing directory services infrastructure.
    '15.0':
      severity: medium
    '14.0':
      severity: medium
    '13.0':
      severity: high
      benchmarks:
        - disa_stig
tags:
  - cisv8
