id: os_system_wide_applications_configure
title: Ensure Appropriate Permissions Are Enabled for System Wide Applications
discussion: |
  Applications in the System Applications Directory (/Applications) _MUST_ not be world-writable.
references:
  nist:
    cce:
      macos_15:
        - CCE-94314-2
      macos_14:
        - CCE-92911-7
      macos_13:
        - CCE-91899-5
      monterey:
        - CCE-91117-2
      big_sur:
        - CCE-85514-8
  cis:
    benchmark:
      macos_15:
        - 5.1.5 (level 1)
      macos_14:
        - 5.1.5 (level 1)
      macos_13:
        - 5.1.5 (level 1)
      monterey:
        - 5.1.5 (level 1)
      big_sur:
        - 5.1.5 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    check: |
      /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 -ls | /usr/bin/wc -l | /usr/bin/xargs
    result:
      integer: 0
    fix: |
      [source,bash]
      ----
      IFS=$'\n'
      for apps in $( /usr/bin/find /Applications -iname "*\.app" -type d -perm -2 ); do
        /bin/chmod -R o-w "$apps"
      done
      ----
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    monterey:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    big_sur:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
