id: os_sshd_client_alive_interval_configure
title: Configure SSHD ClientAliveInterval to $ODV
discussion: |
  If SSHD is enabled then it _MUST_ be configured with the Client Alive Interval set to $ODV.

  Sets a timeout interval in seconds after which if no data has been received from the client, sshd(8) will send a message through the encrypted channel to request a response from the client.

  This setting works in conjunction with ClientAliveCountMax to determine the termination of the connection after the threshold has been reached.

  NOTE: This setting is not intended to manage idle user sessions where there is no input from the client. Its purpose is to monitor for interruptions in network connectivity and force the session to terminate after the connection appears to be broken.

  NOTE: On macOS 15.2 and higher the SSH configuration can be reset to the macOS default by running /usr/libexec/reset-ssh-configuration.
references:
  nist:
    cce:
      macos_15:
        - CCE-94304-3
      macos_14:
        - CCE-92899-4
      macos_13:
        - CCE-91887-0
      monterey:
        - CCE-91008-3
      big_sur:
        - CCE-85457-0
      catalina:
        - CCE-84793-9
    800-53r5:
      - SC-10
      - AC-12
    800-171r3:
      - 03.01.11
      - 03.13.09
  disa:
    cci:
      - CCI-001133
    srg:
      - SRG-OS-000163-GPOS-00072
    disa_stig:
      macos_15:
        - APPL-15-000051
      macos_14:
        - APPL-14-000051
      macos_13:
        - APPL-13-000051
      monterey:
        - APPL-12-000051
      big_sur:
        - APPL-11-000051
      catalina:
        - AOSX-15-000051
    cmmc:
      - AC.L2-3.1.11
      - SC.L2-3.13.9
platforms:
  macOS:
    check: $OS_VALUE
    result: $OS_VALUE
    fix: $OS_VALUE
    '15.0':
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/sbin/sshd -G | /usr/bin/awk '/clientaliveinterval/{print $2}'
      fix: |-
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        /usr/bin/grep -qxF 'clientaliveinterval $ODV' "${include_dir}01-mscp-sshd.conf" 2>/dev/null || echo "clientaliveinterval $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
      result:
        integer: $ODV
    '14.0':
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/sbin/sshd -G | /usr/bin/awk '/clientaliveinterval/{print $2}'
      fix: |-
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        /usr/bin/grep -qxF 'clientaliveinterval $ODV' "${include_dir}01-mscp-sshd.conf" 2>/dev/null || echo "clientaliveinterval $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
      result:
        integer: $ODV
    '13.0':
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/sbin/sshd -T | /usr/bin/awk '/clientaliveinterval/{print $2}'
      fix: |-
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        /usr/bin/grep -qxF 'clientaliveinterval $ODV' "${include_dir}01-mscp-sshd.conf" 2>/dev/null || echo "clientaliveinterval $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
      result:
        integer: $ODV
    monterey:
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/sbin/sshd -T | /usr/bin/awk '/clientaliveinterval/{print $2}'
      fix: |-
        [source,bash]
        ----
        include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

        if [[ -z $include_dir ]]; then
          /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
        fi

        /usr/bin/grep -qxF 'clientaliveinterval $ODV' "${include_dir}01-mscp-sshd.conf" 2>/dev/null || echo "clientaliveinterval $ODV" >> "${include_dir}01-mscp-sshd.conf"

        for file in $(ls ${include_dir}); do
          if [[ "$file" == "100-macos.conf" ]]; then
              continue
          fi
          if [[ "$file" == "01-mscp-sshd.conf" ]]; then
              break
          fi
          /bin/mv ${include_dir}${file} ${include_dir}20-${file}
        done
        ----
      result:
        integer: $ODV
    big_sur:
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/bin/grep -c "^ClientAliveInterval $ODV" /etc/ssh/sshd_config
      fix: |-
        [source,bash]
        ----
        /usr/bin/sed -i.bak 's/.*ClientAliveInterval.*/ClientAliveInterval $ODV/' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
        ----
      result:
        integer: 1
    catalina:
      severity: medium
      benchmarks:
        - disa_stig
      check: /usr/bin/grep -c "^ClientAliveInterval $ODV " /etc/ssh/sshd_config
      fix: |-
        [source,bash]
        ----
        /usr/bin/sed -i.bak 's/.*ClientAliveInterval.*/ClientAliveInterval $ODV /' /etc/ssh/sshd_config; /bin/launchctl kickstart -k system/com.openssh.sshd
        ----
      result:
        integer: 1
odv:
  hint: Number of seconds.
  recommended: 900
  stig: 900
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
ddm_info:
  declarationtype: com.apple.configuration.services.configuration-files
  service: com.apple.sshd
  config_file: sshd_config
  configuration_key: ClientAliveInterval
  configuration_value: $ODV
