id: os_world_writable_system_folder_configure
title: Ensure No World Writable Files Exist in the System Folder
discussion: |
  Folders in /System/Volumes/Data/System _MUST_ not be world-writable.
references:
  nist:
    cce:
      macos_15:
        - CCE-94327-4
      macos_14:
        - CCE-92924-0
      macos_13:
        - CCE-91912-6
      monterey:
        - CCE-91121-4
      big_sur:
        - CCE-85518-9
  cis:
    benchmark:
      macos_15:
        - 5.1.6 (level 1)
      macos_14:
        - 5.1.6 (level 1)
      macos_13:
        - 5.1.6 (level 1)
      monterey:
        - 5.1.6 (level 1)
      big_sur:
        - 5.1.6 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    check: $OS_VALUE
    result:
      integer: 0
    fix: $OS_VALUE
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
      check: /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -vE "downloadDir|locks" | /usr/bin/wc -l | /usr/bin/xargs
      fix: |-
        [source,bash]
        ----
        IFS=$'\n'
        for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -vE "downloadDir|locks" ); do
          /bin/chmod -R o-w "$sysPermissions"
        done
        ----
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
      check: /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -vE "downloadDir|locks" | /usr/bin/wc -l | /usr/bin/xargs
      fix: |-
        [source,bash]
        ----
        IFS=$'\n'
        for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -vE "downloadDir|locks" ); do
          /bin/chmod -R o-w "$sysPermissions"
        done
        ----
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
      check: /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -v "downloadDir" | /usr/bin/wc -l | /usr/bin/xargs
      fix: |-
        [source,bash]
        ----
        IFS=$'\n'
        for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -v "downloadDir" ); do
          /bin/chmod -R o-w "$sysPermissions"
        done
        ----
    monterey:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
      check: /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -v "Drop Box" | /usr/bin/wc -l | /usr/bin/xargs
      fix: |-
        [source,bash]
        ----
        IFS=$'\n'
        for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -v "Drop Box" ); do
          /bin/chmod -R o-w "$sysPermissions"
        done
        ----
    big_sur:
      benchmarks:
        - cis_lvl1
        - cis_lvl2
      check: /usr/bin/find /System/Volumes/Data/System -type d -perm -2 -ls | /usr/bin/grep -v "Drop Box" | /usr/bin/wc -l | /usr/bin/xargs
      fix: |-
        [source,bash]
        ----
        IFS=$'\n'
        for sysPermissions in $( /usr/bin/find /System/Volumes/Data/System -type d -perm -2 | /usr/bin/grep -v "Drop Box" ); do
          /bin/chmod -R o-w "$sysPermissions"
        done
        ----
tags:
  - cisv8
