id: system_settings_wake_network_access_disable
title: Ensure Wake for Network Access Is Disabled
discussion: |
  Wake for network access _MUST_ be disabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94410-8
      macos_14:
        - CCE-93005-7
      macos_13:
        - CCE-91995-1
  cis:
    benchmark:
      macos_15:
        - 2.9.3 (level 1)
      macos_14:
        - 2.9.3 (level 1)
      macos_13:
        - 2.9.3 (level 1)
    controls_v8:
      - 4.8
platforms:
  macOS:
    check: |
      /usr/bin/pmset -g custom | /usr/bin/awk '/womp/ { sum+=$2 } END {print sum}'
    result:
      integer: 0
    fix: |
      [source,bash]
      ----
      /usr/bin/pmset -a womp 0
      ----
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
