id: system_settings_time_machine_auto_backup_enable
title: Configure Time Machine for Automatic Backups
discussion: |
  Automatic backups _MUST_ be enabled when using Time Machine.
references:
  nist:
    cce:
      macos_15:
        - CCE-94402-5
      macos_14:
        - CCE-92997-6
      macos_13:
        - CCE-91987-8
  cis:
    benchmark:
      macos_15:
        - 2.3.4.1 (level 2)
      macos_14:
        - 2.3.4.1 (level 2)
      macos_13:
        - 2.3.4.1 (level 2)
    controls_v8:
      - 11.2
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.TimeMachine')\
      .objectForKey('AutoBackup').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.TimeMachine:
    AutoBackup: true
