id: system_settings_password_hints_disable
title: Disable Password Hints
discussion: |
  Password hints _MUST_ be disabled.

  Password hints leak information about passwords that are currently in use and can lead to loss of confidentiality.
references:
  nist:
    cce:
      macos_15:
        - CCE-94382-9
      macos_14:
        - CCE-92978-6
      macos_13:
        - CCE-91967-0
    800-53r5:
      - IA-6
    800-171r3:
      - 03.05.11
  disa:
    cci:
      - CCI-000206
    srg:
      - SRG-OS-000079-GPOS-00047
    disa_stig:
      macos_15:
        - APPL-15-003012
      macos_14:
        - APPL-14-003012
      macos_13:
        - APPL-13-003012
    cmmc:
      - IA.L2-3.5.11
  cis:
    benchmark:
      macos_15:
        - 2.10.5 (level 1)
      macos_14:
        - 2.10.5 (level 1)
      macos_13:
        - 2.10.5 (level 1)
    controls_v8:
      - 4.1
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
      .objectForKey('RetriesUntilHint').js
      EOS
    result:
      integer: 0
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.loginwindow:
    RetriesUntilHint: 0
