id: system_settings_software_update_app_update_enforce
title: Enforce Software Update App Update Updates Automatically
discussion: |
  Software Update _MUST_ be configured to enforce automatic updates of App Updates is enabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94395-1
      macos_14:
        - CCE-92990-1
      macos_13:
        - CCE-91980-3
  cis:
    benchmark:
      macos_15:
        - 1.5 (level 1)
      macos_14:
        - 1.5 (level 1)
      macos_13:
        - 1.5 (level 1)
    controls_v8:
      - 7.3
      - 7.4
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
      .objectForKey('AutomaticallyInstallAppUpdates').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.SoftwareUpdate:
    AutomaticallyInstallAppUpdates: true
