id: system_settings_loginwindow_prompt_username_password_enforce
title: Configure Login Window to Prompt for Username and Password
discussion: |
  The login window _MUST_ be configured to prompt all users for both a username and a password.

  By default, the system displays a list of known users on the login window, which can make it easier for a malicious user to gain access to someone else's account. Requiring users to type in both their username and password mitigates the risk of unauthorized users gaining access to the information system.
references:
  nist:
    cce:
      macos_15:
        - CCE-94380-3
      macos_14:
        - CCE-92976-0
      macos_13:
        - CCE-91965-4
    800-53r5:
      - IA-2
    800-171r3:
      - 03.05.01
  disa:
    cci:
      - CCI-000764
    srg:
      - SRG-OS-000104-GPOS-00051
    disa_stig:
      macos_15:
        - APPL-15-005052
      macos_14:
        - APPL-14-005052
      macos_13:
        - APPL-13-005052
    cmmc:
      - IA.L1-3.5.1
      - IA.L1-3.5.2
  cis:
    benchmark:
      macos_15:
        - 2.10.4 (level 1)
      macos_14:
        - 2.10.4 (level 1)
      macos_13:
        - 2.10.4 (level 1)
    controls_v8:
      - 4.1
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
      .objectForKey('SHOWFULLNAME').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
    '13.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cmmc_lvl1
  - cnssi-1253_moderate
mobileconfig_info:
  com.apple.loginwindow:
    SHOWFULLNAME: true
