id: system_settings_wifi_menu_enable
title: Enable Wifi Menu
discussion: |
  The WiFi menu _MUST_ be enabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94414-0
      macos_14:
        - CCE-93010-7
      macos_13:
        - CCE-92000-9
  cis:
    benchmark:
      macos_15:
        - 2.4.1 (level 1)
      macos_14:
        - 2.4.1 (level 1)
      macos_13:
        - 2.4.1 (level 1)
    controls_v8:
      - 4.8
      - 12.6
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
      .objectForKey('WiFi').js
      EOS
    result:
      integer: 18
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.controlcenter:
    WiFi: 18
