id: system_settings_software_update_enforce
title: Enforce Software Update Automatically
discussion: |
  Software Update _MUST_ be configured to enforce automatic update is enabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94397-7
      macos_14:
        - CCE-92992-7
      macos_13:
        - CCE-91982-9
    800-53r5:
      - SI-2(5)
    800-171r3:
      - 3.14.1
      - 3.14.2
      - 3.13.3
  cis:
    benchmark:
      macos_15:
        - 1.2 (level 1)
      macos_14:
        - 1.2 (level 1)
      macos_13:
        - 1.2 (level 1)
    controls_v8:
      - 7.3
      - 7.4
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
      .objectForKey('AutomaticCheckEnabled').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.SoftwareUpdate:
    AutomaticCheckEnabled: true
