id: system_settings_loginwindow_loginwindowtext_enable
title: Configure Login Window to Show A Custom Message
discussion: |
  The login window _MUST_ be configured to show a custom access warning message.
references:
  nist:
    cce:
      macos_15:
        - CCE-94379-5
      macos_14:
        - CCE-92975-2
      macos_13:
        - CCE-91964-7
  cis:
    benchmark:
      macos_15:
        - 2.10.3 (level 1)
      macos_14:
        - 2.10.3 (level 1)
      macos_13:
        - 2.10.3 (level 1)
    controls_v8:
      - 4.1
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS | /usr/bin/base64
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.loginwindow')\
      .objectForKey('LoginwindowText').js
      EOS
    result:
      base64: $ODV
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
odv:
  hint: Organization's approved message.
  recommended: Center for Internet Security Test Message
  cis_lvl1: Center for Internet Security Test Message
  cis_lvl2: Center for Internet Security Test Message
tags:
  - cisv8
mobileconfig_info:
  com.apple.loginwindow:
    LoginwindowText: $ODV
