id: system_settings_bluetooth_menu_enable
title: Enable Bluetooth Menu
discussion: |
  The bluetooth menu _MUST_ be enabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94353-0
      macos_14:
        - CCE-92950-5
      macos_13:
        - CCE-91937-3
  cis:
    benchmark:
      macos_15:
        - 2.4.2 (level 1)
      macos_14:
        - 2.4.2 (level 1)
      macos_13:
        - 2.4.2 (level 1)
    controls_v8:
      - 4.8
      - 13.9
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.controlcenter')\
      .objectForKey('Bluetooth').js
      EOS
    result:
      integer: 18
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.controlcenter:
    Bluetooth: 18
