id: system_settings_bluetooth_menu_enable
title: Enable Bluetooth Menu
discussion: |
  The bluetooth menu _MUST_ be enabled.
check: |

  if [ -n "${CACHED_PROFILES_FILE:-}" ] && [ -f "${CACHED_PROFILES_FILE}" ]; then
    /usr/bin/grep -qE 'Bluetooth = 18' "${CACHED_PROFILES_FILE}" && echo 18 || echo 0
  else
    /usr/bin/sudo /usr/bin/profiles -P -o stdout | /usr/bin/grep -qE 'Bluetooth = 18' && echo 18 || echo 0
  fi
result:
  integer: 18
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-94353-0
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r3:
    - N/A
  cis:
    benchmark:
      - 2.4.2 (level 1)
    controls v8:
      - 4.8
      - 13.9
macOS:
  - '15.0'
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: true
mobileconfig_info:
  com.apple.controlcenter:
    Bluetooth: 18
