id: system_settings_software_update_download_enforce
title: Enforce Software Update Downloads Updates Automatically
discussion: |
  Software Update _MUST_ be configured to enforce automatic downloads of updates is enabled.
references:
  nist:
    cce:
      macos_15:
        - CCE-94396-9
      macos_14:
        - CCE-92991-9
      macos_13:
        - CCE-91981-1
  cis:
    benchmark:
      macos_15:
        - 1.3 (level 1)
      macos_14:
        - 1.3 (level 1)
      macos_13:
        - 1.3 (level 1)
    controls_v8:
      - 7.3
      - 7.4
platforms:
  macOS:
    check: |
      /usr/bin/osascript -l JavaScript << EOS
      $.NSUserDefaults.alloc.initWithSuiteName('com.apple.SoftwareUpdate')\
      .objectForKey('AutomaticDownload').js
      EOS
    result:
      string: 'true'
    fix: |
      This is implemented by a Configuration Profile.
    '15.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '14.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
    '13.0':
      benchmarks:
        - cis_lvl1
        - cis_lvl2
tags:
  - cisv8
mobileconfig_info:
  com.apple.SoftwareUpdate:
    AutomaticDownload: true
