id: audit_acls_folders_configure
title: Configure Audit Log Folder to Not Contain Access Control Lists
discussion: |
  The audit log folder _MUST_ not contain access control lists (ACLs).

  Audit logs contain sensitive data about the system and users. This rule ensures that the audit service is configured to create log folders that are readable and writable only by system administrators in order to prevent normal users from reading audit logs.
references:
  nist:
    cce:
      macos_15:
        - CCE-94102-1
      macos_14:
        - CCE-92702-0
      macos_13:
        - CCE-91702-1
      monterey:
        - CCE-90852-5
      big_sur:
        - CCE-85252-5
      catalina:
        - CCE-84704-6
    800-53r5:
      - AU-9
    800-171r3:
      - 03.03.08
  disa:
    cci:
      - CCI-000162
      - CCI-000162
      - CCI-000163
      - CCI-000164
      - CCI-001493
      - CCI-001494
      - CCI-001495
    srg:
      - SRG-OS-000256-GPOS-00097
      - SRG-OS-000057-GPOS-00027
      - SRG-OS-000059-GPOS-00029
      - SRG-OS-000257-GPOS-00098
      - SRG-OS-000258-GPOS-00099
      - SRG-OS-000058-GPOS-00028
    disa_stig:
      macos_15:
        - APPL-15-000031
      macos_14:
        - APPL-14-000031
      macos_13:
        - APPL-13-000031
      monterey:
        - APPL-12-000031
      big_sur:
        - APPL-11-000031
      catalina:
        - AOSX-15-000031
    cmmc:
      - AU.L2-3.3.8
  cis:
    benchmark:
      macos_15:
        - 3.5 (level 1)
      macos_14:
        - 3.5 (level 1)
      macos_13:
        - 3.5 (level 1)
      monterey:
        - 3.5 (level 1)
      big_sur:
        - 3.5 (level 1)
    controls_v8:
      - 3.3
platforms:
  macOS:
    check: $OS_VALUE
    result:
      integer: 0
    fix: $OS_VALUE
    '15.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
      check: /bin/ls -lde /var/audit | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N /var/audit
        ----
    '14.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
      check: /bin/ls -lde /var/audit | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N /var/audit
        ----
    '13.0':
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
      check: /bin/ls -lde /var/audit | /usr/bin/awk '{print $1}' | /usr/bin/grep -c ":"
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N /var/audit
        ----
    monterey:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
      check: '/bin/ls -lde $(/usr/bin/grep ''^dir'' /etc/security/audit_control | /usr/bin/awk -F: ''{print $2}'') | /usr/bin/awk ''{print $1}'' | /usr/bin/grep -c ":"'
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
        ----
    big_sur:
      severity: medium
      benchmarks:
        - cis_lvl1
        - cis_lvl2
        - disa_stig
      check: '/bin/ls -lde $(/usr/bin/grep ''^dir'' /etc/security/audit_control | /usr/bin/awk -F: ''{print $2}'') | /usr/bin/awk ''{print $1}'' | /usr/bin/grep -c ":"'
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
        ----
    catalina:
      severity: medium
      benchmarks:
        - disa_stig
      check: '/bin/ls -lde $(/usr/bin/grep ''^dir'' /etc/security/audit_control | /usr/bin/awk -F: ''{print $2}'') | /usr/bin/awk ''{print $1}'' | /usr/bin/grep -c ":"'
      fix: |-
        [source,bash]
        ----
        /bin/chmod -N $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
        ----
tags:
  - 800-53r5_low
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cisv8
  - cnssi-1253_low
  - cnssi-1253_high
  - cmmc_lvl2
  - cnssi-1253_moderate
  - cnssi-1253
